name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  sast-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Snyk CLI
        run: npm install -g snyk
      - name: Run SAST with Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk code test
  docker-build-and-deploy:
    runs-on: ubuntu-latest
    needs: sast-analysis
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:latest .
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest
  dast-scan:
    runs-on: ubuntu-latest
    needs: docker-build-and-deploy
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install OWASP ZAP
        run: |
          sudo apt-get update
          sudo apt-get install -y zaproxy
      - name: Run ZAP Scan
        run: zap-baseline.py -t http://localhost:3000 -r zap-report.html